.pragma library

// Character-grid sprites. "." is transparent; every other character indexes
// the sprite's own palette. All original artwork.

var PLAYER = {
  palette: { o:"#20252b", h:"#c8552b", s:"#e8b48a", e:"#20252b",
             c:"#3f6f9c", k:"#2b4d6e", b:"#5a3f28" },
  down: [
    "................",
    "................",
    "....oooooooo....",
    "...ohhhhhhhho...",
    "...ohhhhhhhho...",
    "..oooooooooooo..",
    "....osssssso....",
    "....osesseso....",
    "....osssssso....",
    ".....oooooo.....",
    "...occcccccco...",
    "..occcccccccco..",
    "..occcccccccco..",
    "...okccccccko...",
    "....obb..bbo....",
    ".....oo..oo....."
  ]
}

// Shared creature body shapes. A species is an archetype plus its own palette.
var ARCHETYPES = {
  blob: [
    "................",
    ".....oooooo.....",
    "...ooaaaaaaoo...",
    "..oaaaaaaaaaao..",
    ".oaaaaaaaaaaaao.",
    ".oaaeeaaaaeeaao.",
    ".oaapeaaaapeaao.",
    ".oaaaaaaaaaaaao.",
    ".oaaaaaddaaaaao.",
    ".obaaaaaaaaaabo.",
    "..obbaaaaaabbo..",
    "...oobbbbbboo...",
    "....oo....oo....",
    "...oddo..oddo...",
    "................",
    "................"
  ],
  serpent: [
    "................",
    "..oooo..........",
    ".oaaaao.........",
    ".oeeaao.........",
    ".opeaaoo........",
    ".oaaaaao........",
    "..oaaaaoo.......",
    "...oaaaaoo......",
    "....ooaaaaoo....",
    "......ooaaaaoo..",
    "........oaaaao..",
    "........obaaco..",
    ".........obcco..",
    "..........oooo..",
    "................",
    "................"
  ],
  bird: [
    "................",
    "......oooo......",
    ".....oaaaao.....",
    ".....oeeaao.....",
    "...ffopeaao.....",
    "...ffoaaaaoo....",
    "....ooaaaaaao...",
    "...oaabbbbaaao..",
    "..oaabbbbbbaao..",
    "..oaaabbbbaaao..",
    "...oaaaaaaaao...",
    "....ooaaaaoo....",
    "......oddo......",
    ".....od..do.....",
    "................",
    "................"
  ],
  fish: [
    "................",
    "................",
    "........oooo....",
    ".ooo..ooaaaaoo..",
    ".occoooaaaaaaao.",
    ".occcoaaeeaaaaao",
    ".occccaaapeaaaao",
    ".occcoaaaaaaaaao",
    ".occoooaaaaaaao.",
    ".ooo..ooaaaaoo..",
    "..........oooo..",
    "................",
    "................",
    "................",
    "................",
    "................"
  ],
  critter: [
    "................",
    "....oo..........",
    "...oaao....oo...",
    "...oaaao..oaao..",
    "..oaeeaao.ocao..",
    "..oapeaaaoocao..",
    "..oaaaaaaaocao..",
    ".oaaaaaaaaacao..",
    ".oaaaaaaaaaaao..",
    ".obaaaaaaaaao...",
    "..obbaaaaaao....",
    "...ooo..ooo.....",
    "..odd....ddo....",
    "................",
    "................",
    "................"
  ],
  fluff: [
    "................",
    "....oooooo......",
    "..oocccccco.....",
    ".occccccccco....",
    "occcccccccccoo..",
    "occcccccccaaao..",
    "occccccccaeeao..",
    "occccccccapeao..",
    "occcccccccaaao..",
    ".occcccccccco...",
    "..occcccccco....",
    "...oo.oo.oo.....",
    "...od..od..o....",
    "................",
    "................",
    "................"
  ],
  bat: [
    "................",
    "..o.........o...",
    ".obo.oooo..obo..",
    ".obboaaaaoobbo..",
    "obbbbaeeaobbbbo.",
    "obbbbapeaobbbbo.",
    ".obbbaaaaabbbo..",
    "..oobaaaaabooo..",
    "....oaaaaao.....",
    "....oabbaao.....",
    ".....obbao......",
    "......oooo......",
    "................",
    "................",
    "................",
    "................"
  ],
  ghost: [
    "................",
    "................",
    ".....oooooo.....",
    "...ooaaaaaaoo...",
    "..oaaaaaaaaaao..",
    ".oaaeeaaaaeeao..",
    ".oaapeaaaapeao..",
    ".oaaaaaaaaaaao..",
    ".oaaaaaaaaaaao..",
    ".oaaaaaaaaaaao..",
    ".obaaaaaaaaabo..",
    ".oboaboabaobao..",
    ".o.oo.oo.oo.oo..",
    "................",
    "................",
    "................"
  ],
  beetle: [
    "................",
    "....o......o....",
    "....o......o....",
    ".....o....o.....",
    "....oooooooo....",
    "...oaaaaaaaao...",
    "..oaeeaaaaeeao..",
    ".ocapeaaaapeaco.",
    ".ocaabaaaabaaco.",
    ".ocaaabaabaaaco.",
    "..oaaaabbaaaao..",
    "...oaaaaaaaao...",
    "....oooooooo....",
    "...od.o..o.do...",
    "................",
    "................"
  ],
  stone: [
    "................",
    "................",
    "......oooo......",
    "....ooaaaaoo....",
    "...oaaaaaaaao...",
    "..oaeeaaaaeeao..",
    "..oapeaaaapeao..",
    ".ocaaaaaaaaaaco.",
    ".ocbaaaaaaaabco.",
    ".ocbbaaaaaabbco.",
    "..obbbbbbbbbbo..",
    "..oobbbbbbbboo..",
    "....oo....oo....",
    "...odo....odo...",
    "................",
    "................"
  ],
  sprite: [
    "................",
    "......oooo......",
    ".....oaaaao.....",
    ".....oeeeeo.....",
    ".....opeepo.....",
    "..o..oaaaao..o..",
    ".oco.oaaaao.oco.",
    ".occooaaaaoocco.",
    "..occcoaaoccco..",
    "...oococcooo....",
    "......oaao......",
    "......oaao......",
    ".....od..do.....",
    "................",
    "................",
    "................"
  ]
}
